### ISSUE TITLE
盒子启动不起来 - -

### ISSUE THREAD

**Issue by CommanderXL** [YIXUNFE/toolbox#1]
通过 `electron toolbox`命令启动了electron应用，但是应用是全白色。

是还需要编译其他的文件么？

**Comment by YIXUNFE** [comment]
应用会加载配置文件 `yixunfe_toolbox.config`，请确保这个文件在应用的同一级目录下。

目前需要手动放置一下 :smile: 

后续会加上一些友善的处理。
